version: '3'
services:
  vigilo-rabbit-test-local:
    image: rabbitmq:3-management
    hostname: my-rabbit
    ports:
      - 9999:15672
      - 5672:5672
      - 5671:5671
    environment:
      - RABBITMQ_DEFAULT_USER=foo
      - RABBITMQ_DEFAULT_PASS=bar
      - RABBITMQ_DEFAULT_VHOST=virtual.test